### model
model_name_or_path: /mnt/madehua/model/meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: food172_text_retrieval_10
template: llama3
cutoff_len: 512
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: /mnt/madehua/model/checkpoints/llama3_food172
logging_steps: 10
save_strategy: "epoch"
plot_loss: true
overwrite_output_dir: false

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
do_eval: false
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: 'no'
eval_steps: 500
