### model
model_name_or_path: /mnt/madehua/model/llava-hf/llava-1.5-7b-hf

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: food101_retrieval_no_similarity_5
template: llava
cutoff_len: 1024
max_samples: 100000000
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: /mnt/madehua/model/checkpoints/llava1.5-7b-retrieval-no-similarity-food101
logging_steps: 10
save_strategy: "epoch"
#save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
do_eval: false
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

### prediction
do_predict: false
